### ISSUE TITLE
Search in pdf file

### ISSUE THREAD

**Issue by acitjazz** [barryvdh/laravel-snappy#115]
can i search text or string  inside PDF files ?

**Comment by barryvdh** [comment]
no

**Comment by Sanjibadhikari** [comment]
NAMASTE AND WARM GREETINGS NEPAL MOUNTAIN GUIDE TEAM
Nepal Planet Treks & Expeditions welcomes you to Nepal the country of the Himalayas, started in 2014 Nepal Planet Treks & Expeditions is one the new and innovated agencies in Nepal. Our Managing Director/Trekking Guide Mr. Sanjib Adhikari has over 18 years of trekking experience and always looks for the newest and unexplored routes to increase your trekking experience. Offering all activities such as; trekking, touring, mountaineering, adventure sports, volunteering, paragliding, jungle safaris, mountain flights and many more Nepal Planet Treks & Expeditions promises you a lifetime of memories on a single trip! Nepal Planet Treks & Expeditions offers the newest way of trekking by letting our guests modify the routes to just explore a bit further in to the beautiful landscape of Nepal. Dealing in sustainable tourism we provide jobs for the local communities by hiring porters directly from the local villages, booking at the local tea houses provides a sustainable income for the rural areas in Nepal. Our Nepal Mountain Guide Team provides you with the best service so that you as our valued guest can enjoy the utmost of your well-deserved holiday/trek. In our team...
