### ISSUE TITLE
inline() not working

### ISSUE THREAD

**Issue by AhamedKashif** [barryvdh/laravel-snappy#180]
I am using laravel-snappy to generate pdfs and show them in the browser. I am getting a blank page in return.The code I am using is this.

return PDF::loadView('emails.flightInvoice', $data)->inline();
I used the below code to save the PDF and it is working.

PDF::loadView('emails.flightInvoice', $data')->save('invoice.pdf');
can anyone please help me with this?

**Comment by jamesmuldrow** [comment]
having the same issue. Currently searching for the answer

**Comment by barryvdh** [comment]
Can you try of ->output() returns anything?

**Comment by Shinasoshi** [comment]
I have the same problem. I use windows(maybe it matters).
When  I use save() , pdf file is  saved in public directory without problems.
When i use download(), inline(), stream(), output() nothing happens. Just blank website and nothing is getting downloaded.

 Any clue why?

**Comment by Shinasoshi** [comment]
Well. I fixed the problem. Still dunno why, but it didnt work in this method. Had to move this response to parrent method, then worked correct.

**Comment by lokmanhakim** [comment]
what exactly did you do to make it work @Shinasoshi

**Comment by toonevdb** [comment]
The inline method does not exist, but stream works. Docs should probably be updated.
Code below works for me:

```
$pdf = PDF::loadView('pdf_html_view');
return $pdf->stream();
```

**Comment by byustephen** [comment]
For me stream() and inline() both work. I found out that Chrome has a setting that can force downloading of streaming pdfs. I turned that off and it finally works. 

Here's the post for more info:

https://support.google.com/chrome/answer/6213030?hl=en

**Comment by bakerstreetsystems** [comment]
I'm having the same problem as listed above and thought I'd add a little more information.

When I use the `inline` method on my local dev machine (Mac), everything works great. But when I deploy to my Ubuntu server, it returns something like the attached image: 
<img width="219" alt="Screen Shot 2019-07-10 at 3 03 59 PM" src="https://user-images.githubusercontent.com/5008697/61004802-0cc68e00-a324-11e9-88e2-1d3c794d7375.png">

But the `download` method works fine on both local dev machine and production server. 

I'd like to be able to stream the pdf rather than immediately save it as a pdf. Any other advice?
