### ISSUE TITLE
variables don't work?

### ISSUE THREAD

**Issue by olebulow** [barryvdh/laravel-snappy#19]
Hi Barry,

Maybe I'm doing something wrong but with this code:

$servicecase = Servicecase::find($id);
$pdf = App::make('snappy.pdf.wrapper');
$pdf = PDF::loadView('backend.servicecases.receipt', $servicecase);
return $pdf->setOption('margin-top', 5)->stream();

I can't pull data off the variable: Undefined variable: servicecase

Am i missing something? And can i perhaps use multiple vars?

**Comment by warmwhisky** [comment]
I still don't understand how that works? What do i do to get a variable into the SnappyImage??

Here is my code...

```
$data = array(
                        'relatedOutput' => $relatedOutput
                    );
                    $image = SnappyImage::loadView('catalogue.generate_families', $data );
```

I have tried what seems to be all ways but it still has undefined variable.

**Comment by amirgee007** [comment]
i am also getting the same error i tried like this.

$lotTypes = LotType::all();

    $pdf = PDF::loadView('admin.admin-lots.add',['lotTypes' =>$lotTypes]);
    return $pdf->download('invoice.pdf');

**Comment by amirgee007** [comment]
(1/1) RuntimeExceptionThe exit status code '1' says something went wrong:stderr: "Loading pages (1/6)[> ] 0%[======> ] 10%[========> ] 14%Warning: Failed to load file:///admin/assets/global/plugins/bower_components/morrisjs/morris.css (ignore)Warning: Failed to load file:///admin/assets/global/plugins/bower_components/horizontal-chart/build/css/horizBarChart.css (ignore)Warning: Failed to load file:///admin/assets/admin/css/reset.css (ignore)Warning: Failed to load file:///admin/assets/admin/css/layout.css (ignore)Warning: Failed to load file:///admin/assets/admin/css/components.css (ignore)Warning: Failed to load file:///admin/assets/admin/css/plugins.css (ignore)Warning: Failed to load file:///admin/assets/admin/css/pages/dashboard-projects.css (ignore)Warning: Failed to load file:///admin/assets/admin/css/custom.css (ignore)[===========> ] 19%Warning: Failed to load file:///admin/assets/global/plugins/bower_components/typehead.js/dist/handlebars.js (ignore)Warning: Failed to load file:///admin/assets/global/plugins/bower_components/jquery.sparkline.min/index.js (ignore)Warning: Failed to load file:///admin/assets/global/plugins/bower_components/bootbox/bootbox.js (ignore)Warning: Failed to load file:///admin/assets/global/plugins/bower_components/underscore/underscore-min.js (ignore)Warning: Failed to load file:///admin/assets/global/plugins/bower_components/raphael/raphael-min.js (ignore)Warning: Failed to load file:///admin/assets/admin/js/apps.js (ignore)Warning: Failed to load file:///admin/assets/admin/js/demo.js (ignore)[============> ] 21%[=============> ] 23%[===============> ] 26%[================> ] 28%[============================================================] 100%Counting pages (2/6) [============================================================] Object 1 of 1Resolving links (4/6) [============================================================] Object 1 of 1Loading headers and footers (5/6) Printing pages (6/6)[> ] Preparing[===============> ] Page 1 of 4[==============================> ] Page 2 of 4[=============================================> ] Page 3 of 4[============================================================] Page 4 of 4Done Exit with code 1 due to network error: ContentNotFoundError"stdout: ""command: "C:\wkhtmltopdf\wkhtmltopdf.exe" --lowquality "C:\Windows\TEMP\knp_snappy5986fc2518a255.93096674.html" "C:\Windows\TEMP\knp_snappy5986fc251ee412.43827958.pdf".
--
in AbstractGenerator.php (line 336)
at AbstractGenerator->checkProcessStatus(1, '', 'Loading pages (1/6) [> ] 0% [======> ] 10% [========> ] 14% Warning: Failed to load file:///admin/assets/global/plugins/bower_components/morrisjs/morris.css (ignore) Warning: Failed to load file:///admin/assets/global/plugins/bower_components/horizontal-chart/build/css/horizBarChart.css (ignore) Warning: Failed to load file:///admin/assets/admin/css/reset.css (ignore) Warning: Failed to load file:///admin/assets/admin/css/layout.css (ignore) Warning: Failed to load file:///admin/assets/admin/css/components.css (ignore) Warning: Failed to load file:///admin/assets/admin/css/plugins.css (ignore) Warning: Failed to load file:///admin/assets/admin/css/pages/dashboard-projects.css (ignore) Warning: Failed to load file:///admin/assets/admin/css/custom.css (ignore) [===========> ] 19% Warning: Failed to load file:///admin/assets/global/plugins/bower_components/typehead.js/dist/handlebars.js (ignore) Warning: Failed to load file:///admin/assets/global/plugins/bower_components/jquery.sparkline.min/index.js (ignore) Warning: Failed to load file:///admin/assets/global/plugins/bower_components/bootbox/bootbox.js (ignore) Warning: Failed to load file:///admin/assets/global/plugins/bower_components/underscore/underscore-min.js (ignore) Warning: Failed to load file:///admin/assets/global/plugins/bower_components/raphael/raphael-min.js (ignore) Warning: Failed to load file:///admin/assets/admin/js/apps.js (ignore) Warning: Failed to load file:///admin/assets/admin/js/demo.js (ignore) [============> ] 21% [=============> ] 23% [===============> ] 26% [================> ] 28% [============================================================] 100% Counting pages (2/6) [============================================================] Object 1 of 1 Resolving links (4/6) [============================================================] Object 1 of 1 Loading headers and footers (5/6) Printing pages (6/6) [> ] Preparing [===============> ] Page 1 of 4 [==============================> ] Page 2 of 4 [=============================================> ] Page 3 of 4 [============================================================] Page 4 of 4 Done Exit with code 1 due to network error: ContentNotFoundError ', '"C:\\wkhtmltopdf\\wkhtmltopdf.exe" --lowquality "C:\\Windows\\TEMP\\knp_snappy5986fc2518a255.93096674.html" "C:\\Windows\\TEMP\\knp_snappy5986fc251ee412.43827958.pdf"')in AbstractGenerator.php (line 151)
at AbstractGenerator->generate(array('C:\\Windows\\TEMP\\knp_snappy5986fc2518a255.93096674.html'), 'C:\\Windows\\TEMP\\knp_snappy5986fc251ee412.43827958.pdf', array('lowquality' => true), false)in Pdf.php (line 62)
at Pdf->generate(array('C:\\Windows\\TEMP\\knp_snappy5986fc2518a255.93096674.html'), 'C:\\Windows\\TEMP\\knp_snappy5986fc251ee412.43827958.pdf',array('lowquality' => true))in AbstractGenerator.php (line 180)
at AbstractGenerator->getOutput(array('C:\\Windows\\TEMP\\knp_snappy5986fc2518a255.93096674.html'), array())in AbstractGenerator.php (line 201)

**Comment by joshuafranks** [comment]
Use the `compact()` function to pass an array of the object's variables to the view. 

```
$pdf = PDF::loadView('admin.admin-lots.add', compact('lotTypes'));
return $pdf->download('invoice.pdf');
```

And then you can just access the array through `$lotTypes`.

**Comment by amirgee007** [comment]
yes thanks
Route::get('/download', function () {

    $lotTypes = LotType::all();

    $data = array(
        'lotTypes' => $lotTypes,
    );

    $pdf = PDF::loadView('admin/reports/pdf',$data);
//    return $pdf->setOption('margin-top', 5)->stream();
    return $pdf->download('invoice.pdf');

});
its working also for me
