### ISSUE TITLE
Cross-OS issue

### ISSUE THREAD

**Issue by salarmehr** [barryvdh/laravel-snappy#234]
I use exactly the same code on CentoOS and Linux. 
The html rendering are the same but when I create PDF it is only rendered correctly on the Windows machine.  The pdf is generated on the linux as well but without provided style. 
Any know Linux exclusive issue?

**Comment by psychonetic** [comment]
This issue is related to wkhtmltopdf. I had a similiar issue, when using the native wkhtmltopdf version (there is a know bug with the current version and results in incorrect scaling between different os). Try to use the composer version of wkhtmltopdf and also check your path seperators. Windows uses \ and unix system  /.
