### ISSUE TITLE
--replace function implementation?

### ISSUE THREAD

**Issue by Jaspur** [barryvdh/laravel-snappy#27]
It isn't possible to use the `--replace * <name> <value>` function (from the wkhtmltopdf-docs: Replace [name] with value in header and footer (repeatable)).

**Comment by colejarczyk** [comment]
There is no need to change anything. To use "--replace" argument you must pass associative array:


``
$pdf->setOptions('replace', array('variable_name' => 'variable_vale'));
``

Of course there can be more items in array.
The problem is when you do not use associative array. Whole "--replace" arguments are quoted by function "escapeshellarg" (ie. 'variable_name variable_value'). This cause an error, because proper format is "variable_name" "variable_value" (double quote or single quote doesn't matter). When you pass associative array, key and value of array are separately quoted, which is good.

Code responsible for such behavior is in "AbstractGenerator", lines 409-417.

**Comment by juukie** [comment]
Using `$pdf->setOptions('replace', array('foo' => 'barry baz'));` made the options being added to the wkhtmltopdf, and it is passed as a query param to the view.
However, I was not able to get it replaced in the view. I've tried `<span class="foo"></span>` and `{foo}`.

I've ended up with this workaround. Changing the `subst` function to this, so every query param will be replaced instead of the predefined ones (`'page', 'frompage', 'topage', 'webpage', 'section', 'subsection', 'date', 'isodate', 'time', 'title', 'doctitle', 'sitepage', 'sitepages', 'reference'`):
~~~
function subst() {
        var vars = {};
        var css_selector_classes = [];
        var query_strings_from_url = document.location.search.substring(1).split('&');
        for (var query_string in query_strings_from_url) {
            if (query_strings_from_url.hasOwnProperty(query_string)) {
                var temp_var = query_strings_from_url[query_string].split('=', 2);
                vars[temp_var[0]] = decodeURI(temp_var[1]);
                css_selector_classes.push(temp_var[0]);
            }
        }
        // var css_selector_classes = ['page', 'frompage', 'topage', 'webpage', 'section', 'subsection', 'date', 'isodate', 'time', 'title', 'doctitle', 'sitepage', 'sitepages', 'reference'];
        for (var css_class in css_selector_classes) {
            if (css_selector_classes.hasOwnProperty(css_class)) {
                var element = document.getElementsByClassName(css_selector_classes[css_class]);
                for (var j = 0; j < element.length; ++j) {
                    element[j].textContent = vars[css_selector_classes[css_class]];
                }
            }
        }
}
~~~

Now `<span class="foo"></span>` does get the content `barry baz`.
