### ISSUE TITLE
Unable to get binary on vapor

### ISSUE THREAD

**Issue by dmason30** [barryvdh/laravel-snappy#374]
Trying to migrate code to vapor https://vapor.laravel.com/ but it errors saying the binary does not exist:

```php
'binary' => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'),
```

**Comment by VoineaStefan** [comment]
Hi! 
I have the same issue.
Did you find any solution?

**Comment by drfraker** [comment]
Any luck with this?

**Comment by VoineaStefan** [comment]
No.
Can't work on Vapor!
I have read about compiling your own version of snappy for aws and create a function on Amazon for this, but I didn't try it.

**Comment by barryvdh** [comment]
Did you use the latest version of Vapor? With https://github.com/laravel/vapor-core/pull/29

**Comment by VoineaStefan** [comment]
No. 
I didn't try it with latest version of Vapor

**Comment by dmason30** [comment]
I did notice that recent change and do intend to try again soon we switched to DomPDF as a temporary solution since it is a fair bit slower even for a one page invoice.

**Comment by bossyan** [comment]
I was able to specify the path to the binary, but the `wkhtmltopdf` binary throws an error saying it requires the `libXrender.so` which is not installed in the Laravel Vapor lambda function.

I also tried to use DomPDF as @dmason30 suggested, but I'm getting a read only file system error message that has something to do with a generated font. I was able to copy over the fonts in the lib directory in dompdf to the storage and point to that since dompdf requires those fonts.

Anyone was able to find a solution for both snappy or dompdf?
