### ISSUE TITLE
Font display issue comparatively dompdf pdf

### ISSUE THREAD

**Issue by darshanadaptit** [barryvdh/laravel-snappy#415]
while I use Dompdf library to generate pdf it generates pdf perfectly as my expectation as following the first image. but while I generate pdf with WKHTML with the same format it slightly decreasing font spacing. please let me know if you have any solution. and I am using the "sans-serif" font style in both cases. Thank you.

**pdf by DomPdf working fine**
![100088023-91607080-2e75-11eb-8620-95be33300257](https://user-images.githubusercontent.com/50007020/105357187-75c9da00-5c1a-11eb-9109-c973e81fd26b.jpg)

**pdf by WKHTML decreasing font space.**
![100088226-cbca0d80-2e75-11eb-8930-7e4728a64d4c](https://user-images.githubusercontent.com/50007020/105357247-8c703100-5c1a-11eb-8769-79c74a4cc068.jpg)

**Comment by mralston** [comment]
Encountered a similar issue today migrating from DomPDF to Snappy/WK.

You might find that it isn't the same font. My PHP container (Debian based) only had Dejavu Sans installed, so that's what wkhtmltopdf was using. I was specifying Arial in my CSS, no idea what DomPDF was finally using, but weirdly it wasn't Dejavu Sans, which should have been the only font available to it.

Use fc-list to find out what fonts are available to your runtime environment (if using Linux) and install whatever font you're intending to use if it's not listed.

You might also want to adjust the zoom setting being passed to Snappy.

**Comment by damku999** [comment]
@mralston  Thank you for your response.
I Installed font and set zoom setting also but not worked.
