### ISSUE TITLE
Cannot load library icui18n

### ISSUE THREAD

**Issue by arthurkirkosa** [barryvdh/laravel-snappy#43]
I'm getting this issue

```sh
/var/www/systemo.ro/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --print-media-type --header-right '[page]/[toPage]' '/tmp/knp_snappy544e5ffa54d496.58211283.html' '/tmp/knp_snappy544e5ffa54d496.58211283.pdf'
Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)"
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ProtocolInvalidOperationError
```

**Comment by barryvdh** [comment]
Seems you are missing some library, like `libicu` 
This is probably just a wkhtmltopdf error, not for my wrapper.

**Comment by arthurkirkosa** [comment]
Most likely, I've posted on another thread as well and and got a suggestion to install ```apt-get install libicu48```

but I'm getting
```
sudo apt-get install libicu48
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libicu48 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libicu48' has no installation candidate
```

I'm on ubuntu 14.04

Was hoping for a solution from someone who encountered before since it's related to wkhtmltopdf

**Comment by devinfd** [comment]
I am now also getting both errors. The only thing I did to cause this was a composer update.

**Comment by arthurkirkosa** [comment]
I ended up manually downloading the ubuntu 14.04 binaries for wkhtmltopdf and referenced those in the config

14.04 uses libicu52

**Comment by be-codified** [comment]
Hi, 

can somebody help me?

I am getting:

	RuntimeException in AbstractGenerator.php line 333:
	The exit status code '1' says something went wrong:
	stderr: "Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)" 
	...
	Done 
	Exit with code 1 due to network error: ContentNotFoundError
	"
	stdout: ""
	command: ../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --margin-bottom '20' --margin-left '25' --margin-right '15' --margin-top '10' --page-size 'a4' --footer-font-size '8' --footer-html 'http://someurl/partials/pdfFooter.html' 'http://someurl/offers/view/98/pdf' '/tmp/knp_snappy55bf98100d38f7.63414943.pdf'.

**Comment by devinfd** [comment]
I resolved this by SSH'ing into my server and running `apt-get install libxrender1`. Try that.

Devin Dombrowski
dddesigns3@gmail.com

**Comment by be-codified** [comment]
@devinfd thank you for your effort. I have tried this but does not change my issue.

**Comment by murdaugh** [comment]
I experienced this same error on Ubuntu 14.04 when my code was trying to include an image with special characters in the filename. It was a simple fix to sanitize that data, but it took a while for me to figure out that's what the issue was.

**Comment by be-codified** [comment]
Yep, had same experience.

**Comment by anhuibl** [comment]
I have same issue on Laravel Homestead.
I installed these 3 plugins from composer:
$ composer require h4cc/wkhtmltopdf-amd64 0.12.x
$ composer require h4cc/wkhtmltoimage-amd64 0.12.x
$ composer require barryvdh/laravel-snappy 0.2.x

In my controller, my code is
return PDF::loadView(...)->stream();

And this is my laravel log files: 

[2015-11-19 08:39:08] local.ERROR: exception 'RuntimeException' with message 'The exit status code '1' says something went wrong:
stderr: "Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)" 
Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
[=======>                                                    ] 13%
[===============>                                            ] 26%
[=====================>                                      ] 35%
[========================>                                   ] 40%
[===========================>                                ] 45%
[============================>                               ] 47%
[==============================>                             ] 50%
[============================================================] 100%
Counting pages (2/6)                                               
[============================================================] Object 1 of 1
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Resolving links (4/6)
[============================================================] Object 1 of 1
Loading headers and footers (5/6)                                           
Printing pages (6/6)
[>                                                           ] Preparing
[============================================================] Page 1 of 1
Done                                                                      
Exit with code 1 due to network error: ContentNotFoundError
