### ISSUE TITLE
Error "Class snappy.pdf does not exist"

### ISSUE THREAD

**Issue by larsemil** [barryvdh/laravel-snappy#44]
I followed all info in readme, added it as service and as facade.
I set correct path to binary.

No matter how i do i get the following error:
Class snappy.pdf does not exist (or Class.spanny.pdf.wrapper) does not exist.

What is it that i am missing?

My composer json is like this:

"require": {
                "laravel/framework": "5.0.*",
                "barryvdh/laravel-snappy": "0.2.*",
                "h4cc/wkhtmltopdf-amd64": "0.12.2.1",
                "h4cc/wkhtmltopdf-i386": "0.12.2.1",
                "illuminate/html": "~5.0",
                "knplabs/knp-snappy": "0.3.*"
        },

my controller code for testing is: 
return PDF::loadFile('http://www.github.com')->stream('github.pdf');

**Comment by barryvdh** [comment]
You are sure you added the ServiceProvider correctly?
Did you change the config?

Did you clear the cache (`php artisan cache:clear`), config (`php artisan config:clear`) and compiled filed (`php artisan clear-compiled`)?

**Comment by larsemil** [comment]
Added to providers:
'Barryvdh\Snappy\ServiceProvider',

Added to aliases:
'PDF' => 'Barryvdh\Snappy\Facades\SnappyPdf',
'Image' => 'Barryvdh\Snappy\Facades\SnappyImage',


tried clearing all caches, no luch

**Comment by larsemil** [comment]
In top of controller: 
use PDF;
use Barryvdh\Snappy;

**Comment by larsemil** [comment]
Here is controller where its used: 
https://gitlab.dalnix.se/dalnix/dal-pdf/blob/master/app/Http/Controllers/PdfController.php

**Comment by larsemil** [comment]
I restarted from scratch and this time it worked, so must have missed somehing. Thanks for an awesome project!

**Comment by molzieyy** [comment]
I am running Ubuntu I did this:
My fix:

Installed wkhtmltopdf on my server
sudo apt update
sudo apt install wkhtmltopdf

After successful installation, I find the wkhtmltopdf and create a symlink
find / -name wkhtmltopdf
ln -s /usr/bin/wkhtmltopdf /usr/local/bin/whtmltopdf-amd64

then, change the config/snappy.php like this:
'binary' => 'wkhtmltopdf',
For me, this is the fix for my encountered errors such as 'ssl resources not loading, error 127, libssl error, and many more'
I think it is case to case basis depends on the environment and versions of platforms. Thanks.

My Platform Details:

    Ubuntu 22.04
    Laravel Forge on DigitalOcean
    Laravel 9
    PHP 8.1
