### ISSUE TITLE
Not recognized as an internal or external command

### ISSUE THREAD

**Issue by asivaneswaran** [barryvdh/laravel-snappy#60]
Hi,

I followed the instructions on https://github.com/KnpLabs/snappy#wkhtmltopdf-binary-as-composer-dependencies and I changed the binary of pdf and image in my config file like this:

```
    'pdf' => array(
        'enabled' => true,
        'binary' => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'),
        'timeout' => false,
        'options' => array(),
    ),
    'image' => array(
        'enabled' => true,
        'binary' => base_path('vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64'),
        'timeout' => false,
        'options' => array(),
    ),
```

But I keep getting:
```The exit status code '1' says something went wrong: stderr: "'C:\wamp\www\ccp-kinball-v2\ccp-kinball\vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64' is not recognized as an internal or external command, operable program or batch file. " stdout: "" command: C:\wamp\www\ccp-kinball-v2\ccp-kinball\vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --orientation "landscape" 

```

I don't know what I am doing wrong.

Thanks,
```

**Comment by Luceos** [comment]
The cause is related to your path structure when comparing windows with unix machines. Your configuration file uses a unix path structure `/` and your wamp is configured using `\`, in order to fix this either switch to a proper development stack or use windows paths `\` ;)

You can see it here: C:\wamp\www\ccp-kinball-v2\ccp-kinball\vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64, check the switched slash after _vendor_.

**Comment by asivaneswaran** [comment]
Hey,

I updated it and no luck:
```he exit status code '1' says something went wrong: stderr: "'C:\wamp\www\ccp-kinball-v2\ccp-kinball\vendor\h4cc\wkhtmltopdf-amd64\bin\wkhtmltopdf-amd64' is not recognized as an internal or external command, operable program or batch file. " stdout: ""```

**Comment by surgiie** [comment]
Was a solution to this ever found?...I am having same problem and am having no luck to finding a solution.

**Comment by korimatsu** [comment]
I had the same problem, I saw this video and it works now no need to understand spanish https://www.youtube.com/watch?v=NtQ7BnWo_YA

**Comment by dinanrm** [comment]
Please help me :(

 "message" : "The exit status code '1' says something went wrong:\nstderr: \"Loading pages (1/6)\r\n[>                                                           ] 0%\r[======>                                                     ] 10%\r[============>                                               ] 20%\rWarning: Failed to load file:///dashboard/images/9KzJos4Y1dcWRZoTws0uz8IgsHaDEghNhqGInU8f.jpeg (ignore)\r\n[============================================================] 100%\rCounting pages (2/6)                                               \r\n[============================================================] Object 1 of 1\rResolving links (4/6)                                                       \r\n[============================================================] Object 1 of 1\rLoading headers and footers (5/6)                                           \r\nPrinting pages (6/6)\r\n[>                                                           ] Preparing\r[==============================>                             ] Page 1 of 2\r[============================================================] Page 2 of 2\rDone                                                                      \r\nExit with code 1 due to network error: ContentNotFoundError\r\n\"\nstdout: \"\"\ncommand: C:\\xampp\\htdocs\\PatroliSiber\\patrolisiberCMS\\\"vendor\\wemersonjanuario\\wkhtmltopdf-windows\\bin\\64bit\\wkhtmltopdf\" --lowquality --margin-bottom \"20\" --margin-left \"20\" --margin-right \"20\" --margin-top \"20\" --encoding \"UTF-8\" \"C:\\Users\\DINANR~1\\AppData\\Local\\Temp\\knp_snappy5bd6aff938c910.77159022.html\" \"C:\\Users\\DINANR~1\\AppData\\Local\\Temp\\knp_snappy5bd6aff93a4d75.69308646.pdf\".",

**Comment by iraxaxaidi** [comment]
I followed the solution presented above and the got the following error:
The file 'C:\Users\razaz\AppData\Local\Temp\knp_snappy5d7f74227dbb83.62339559.pdf' was not created (command: C:\xampp\htdocs\EDO_Roster\vendor\wemersonjanuario\wkhtmltopdf-windows\bin\64bit\wkhtmltopdf --lowquality --enable-javascript --javascript-delay "5000" --enable-smart-shrinking --no-stop-slow-scripts "C:\Users\razaz\AppData\Local\Temp\knp_snappy5d7f74227d6c75.83364670.html" "C:\Users\razaz\AppData\Local\Temp\knp_snappy5d7f74227dbb83.62339559.pdf").

**Comment by sohel1999** [comment]
how can i install cpanel this package

**Comment by ifly-leonard** [comment]
I can confirm, this works on Windows 10 in 2022!

**Comment by Expertweblancer** [comment]
> `'binary' => base_path('vendor\wemersonjanuario\wkhtmltopdf-windows\bin\64bit\wkhtmltopdf'),`

Did you solve this problem?

**Comment by Expertweblancer** [comment]
> [iraxaxaidi](/iraxaxaidi)

@iraxaxaidi 

Did you solve this problem?
I faced the exact same issue with you.

**Comment by Anglin-George** [comment]
Install visual studio 2013 redistribute pack. Will solve the problem. 
[https://www.microsoft.com/en-in/download/details.aspx?id=40784](url)
